### ISSUE TITLE
Issue when installing with pip anaconda

### ISSUE THREAD

**Issue by RealEmuCoin** [krischer/mtspec#11]
Hi,

I'm trying to install mtspec on a windows machine.
I'm using anaconda, installed gcc with fortran, numpy, matplotlib, flakes8 and pip

But when I'm trying to install mtspec i got an error (see attached picture)

what's wrong ?

thanks

![issuemtspec](https://cloud.githubusercontent.com/assets/6832184/10733690/208123fa-7c00-11e5-8a81-3d56b2768a8e.jpg)

**Comment by krischer** [comment]
The version on pypi is not compatible with Python 3. I'll update that soon. Until then just download the zipball from github or checkout the repository - the version on Github does support Python 3.

**Comment by RealEmuCoin** [comment]
Thank you

However, I'm facing a new issue, when I try to install setup.py, it says that it doesn't know how to compile .f90 file.

Even if I installed TDM-GCC with fortran option checked, and that the bin folder is in the PATH var

What am I missing ?
![issue2](https://cloud.githubusercontent.com/assets/6832184/10753195/9b101272-7c8f-11e5-8d3d-b4e0dbf961bd.jpg)

**Comment by krischer** [comment]
I'm unfortunately not that well versed on using fortran on windows. Maybe @ThomasLecocq can help?

**Comment by ThomasLecocq** [comment]
Hey,

Is TDM-GCC *before* any other path in the PATH? This is important.

**Comment by krischer** [comment]
No answer in 8 month. Closing for now.
