### ISSUE TITLE
Recovering the phase after deconvolution?

### ISSUE THREAD

**Issue by echavess** [krischer/mtspec#15]
Hi Lion and All;

I am computing spectral ratios / deconvolutions using the function **mt_deconvolve**, however after using this function I can't recover the phase. The phase is important to reconstruct the resulting signal to the time domain. Any ideas how can I recover the phase?? 

Thanks in advance, 

Esteban

**Comment by echavess** [comment]
Solved! 
Closed.

**Comment by megies** [comment]
Care to leave a short hint about your solution? Just in case somebody encounters the same problem in the future..

**Comment by krischer** [comment]
Ping.

Please add a short snippet. Base case you directly make a PR and add it to the documentation. Otherwise a short code snippet in here is also fine and I'll add it to the documentation.

**Comment by echavess** [comment]
Ok. Will do. Also, I'll include a couple of figures here as an example.

**Comment by krischer** [comment]
Great :-) Can you just add it to the tutorial? https://github.com/krischer/mtspec/blob/master/doc/tutorial.rst

**Comment by echavess** [comment]
Yeah! No problem. Don't you think it would nice if I add a small section within the Deconvolution tutorial? ...Computing source time functions using the Empirical Green's function method?

**Comment by krischer** [comment]
Totally! This would be awesome. Examples and documentation are always very very appreciated!

**Comment by echavess** [comment]
I am working with local data. where should I put it to run the snippet?

**Comment by krischer** [comment]
Looks good - the data files are also very small so its okay to include them in the repository. I'll manually merge your changes straight into master as you forked from on older version of mtspec. Thanks a lot!

**Comment by krischer** [comment]
Thanks again :-) I integrated it and its already live in the documentation: http://krischer.github.io/mtspec/tutorial.html#multitaper-deconvolution-for-earthquake-source-studies

**Comment by megies** [comment]
Nice! Thanks @echavess!

**Comment by echavess** [comment]
Cool! @megies and @krischer  Thanks to you guys!
