### ISSUE TITLE
python 3.6, pip install works, conda does not

### ISSUE THREAD

**Issue by kylerbrown** [krischer/mtspec#18]
Error from conda:
```
$ conda install mtspec
 
Fetching package metadata .............
Solving package specifications: .


UnsatisfiableError: The following specifications were found to be in conflict:
  - mtspec -> python 3.4* -> xz 5.0.5
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

```

Pip install works, tests pass.

Thank you for your work on this project!

**Comment by megies** [comment]
I've opened a PR against the conda feedstock, see https://github.com/conda-forge/mtspec-feedstock/pull/4.

**Comment by megies** [comment]
@kylerbrown conda-forge is building that package right now, so it should be in conda-forge channel within a day or so (OSX builds usually take longer)

**Comment by krischer** [comment]
Thanks a bunch @megies!
