### ISSUE TITLE
Is the code calculating the amplitude spectrum or the PSD?

### ISSUE THREAD

**Issue by dmelgarm** [krischer/mtspec#20]
Hi,

I have a silly question, are mtspec and sine_psd calculating the amplitude spectrum or the power spectral density (square of the amplitude spectrum)?

I've looked in the source and in both mtspec and sine_psd the calculated quantity is referred to as "the spectrum" but it's unclear what the actual quantity is.

if you could clarify it would be very helpful. Thank you!

**Comment by krischer** [comment]
Hi,

both should calculate the power spectral density. The documentation for the Fortran `mtspec` package is in general a bit more extensive.

Cheers!

**Comment by krischer** [comment]
f886225a77a183a3a972224ed86e23029b0fd7ac updates the docstrings to specify this.
