### ISSUE TITLE
some problems (errors?) in mt_deconvolve() function and its turorial

### ISSUE THREAD

**Issue by KerstiMinkyung** [krischer/mtspec#26]
Hi, Lion
I have some ideas on your tutorial  for mt_deconvolve() function.
( http://krischer.github.io/mtspec/tutorial.html#multitaper-deconvolution-for-earthquake-source-studies )

1. some problems on the procedure

In original version, the tutorial codes obtained 'decon',
and arranged time index (moving M>N/2 index...), 
and th codes named it 'stf (source time function)'.

**The 'stf (source time function)' here is  the source time function itself.
The codes doesn't have to (or must not) apply low-pass filter to 'stf'.**

And, the codes apply Fourier transform to 'stf' to acquire spectral ration.
**But 'spectral ratio' was already calculated in 'mt_deconvolve', on the previous lines.**
'spectral ratio' have to be defined in the previous lines like
spr = r['spectral_ratio']

The codes draw spectral ratio using the result of Fourier-transformed 'stf',
which produce 'minus' amplitude ratio in x axis 
though target events have much larger amplitudes than that of 'egf.sac'. 

2.  'stf' has always ZERO value at the center of the concerned time.

Following to my procedure described above (in 1.),
'stf' can be defined after arranging time index (move M>N/2 ...) for 'decon'
as your tutorial..

time = np.arange(0, len(decon))*dt
M = np.arange(0, len(decon))
N = len(M)
SeD = np.where(np.logical_and(M >= 0, M <= N / 2))
d1 = decon[SeD]
SeD2 = np.where(np.logical_and(M > N / 2, M <= N +1))
d2 = decon[SeD2]
stf = np.concatenate((d2, d1)) 

But I found **'stf' has always ZERO values at the center of the concerned time,**
ie., 'decon' has always ZERO values at the first time index.

I guess that ..
the number of time index has to be modified like 'M-1' or 'M+1'
(or the first value of 'decon' has to be excluded, 
or the last value of 'decon' has to be considered,)
in the mt_deconvolve() or mtspeclib.mt_deconv_().
though I can't see a source of mtspeclib.mt_deconv_()...

**Comment by krischer** [comment]
Hi @KerstiMinkyung,

thanks for your lengthy explanation and sorry for the slow turn-around time on this.

The Fortran source can be found here: https://github.com/krischer/mtspec/blob/master/mtspec/src/src/mt_deconv.f90

@ThomasLecocq I'm super deep into the deconvolution tutorial and you've initially written it. Can you chime in here?

@KerstiMinkyung If you are certain of your findings, please consider opening a PR to fix it!

**Comment by echavess** [comment]
Hi @KerstiMinkyung and @krischer, 

I was the one writing the last part of the tutorial (for earthquake source studies) and I'm a very active user of this code for performing EGF deconvolution. Effectively, you can remove the next lines from the tutorial, those were very specific for one example I did and are not necessary here (this will change the rest too though):  

```
stf /= stf.max()

# Fourier Transform of the rSTF
Cspec, Cfreq = mtspec(stf, delta=dt, time_bandwidth=2,
                      number_of_tapers=3)
```

However, a couple of comments: 

There is nothing wrong with filtering the SFT as long as you filter around the corner frequency of the main event, otherwise you will be missing information about the source. Then:

"But I found 'stf' has always ZERO values at the center of the concerned time,
ie., 'decon' has always ZERO values at the first time index."

I use the code almost everyday and performs fine. I have not seem this issue before. I have a lot of examples of deconvolutions for my work in Costa Rica that i can show.

**Comment by krischer** [comment]
Hey Esteban,

thanks for chiming in so quick. As long as everything makes sense I'm fine with having an extensive tutorial.

@KerstiMinkyung can you and @echavess figure out the issue with center values of the STF and let me know if I have to do something here? Also if one of you thinks the tutorial should be changed, please open an issue or send a PR!

**Comment by KerstiMinkyung** [comment]
Hi @echavess  and @krischer ,
Thanks for your kind replies, and I'm glad to hear your ideas.

My final goal is to get reliable stress drops from the obtained corner frequencies,
following to Viegas et al. (2010) and Abercrombie (2014, 2015).
I use 'mt_deconvolve' with records of the same station, 
to obtain stable spectral ratio for estimation of the corner frequency.
The corner frequency is what I want to estimate, so I have thought that
* filtering rSTF around the corner frequency of the target event is inadequate ,
- the previous studies above (Viegas et al. (2010), Abercrombie (2014, 2015)) didn’t mention about applying low pass filter to the STF, but the authors stated that the final STF were obtained after stacking single STF.

* a spectral ratio can be defined in ‘mt_deconvolve’ by spr = r['spectral_ratio'], 
so I thought that performing FFT of the low pass filtered rSTF, to obtain a spectral ratio in the tutorial, is a kind of duplicate or excessive procedure. The authors above obtained a ‘clean’ spectral ratio curves are by curve-fitting. 

And… 
* before low pass filtered, rSTF in the tutorial have a center value of zero, which results from the deconvolved time series (decon = r[‘deconvolved]) with the first value of zero. 

Applying low pass filter, but, would be one of solutions as Dr. Esteban recommended, 
Maybe I’m just absorbed in specific procedures.

**Comment by echavess** [comment]
Hi @KerstiMinkyung 

I am working with Rachel Abercrombie, measuring stress drops in Costa Rica. We use this method and it is working fine. I'll be happy to chat with you and show you what we are doing. Feel free to email me at: esteban.j.chaves@una.ac.cr. 

Cheers,

**Comment by KerstiMinkyung** [comment]
Hi @echavess
I'm happy to mail you. Thank you again for sharing your ideas.
